import {MBTIS,CITY_ZONES,normalizeCity,dateInZone,generateOracle,oracleText,validateProfile} from './oracle.js';
const $=id=>document.getElementById(id);const STORAGE_KEY='rihe-profile-v1';let activeOracle=null;let activeProfile=null;let defaultZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai';
for(const type of MBTIS)$('mbti').add(new Option(type,type));
const zones=[...new Set([defaultZone,...Object.values(CITY_ZONES),...(Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):[])])].sort();
for(const zone of zones)$('timezone').add(new Option((Object.entries(CITY_ZONES).find(([city,z])=>z===zone&&!/[a-z]/.test(city))?.[0] || zone.replaceAll('_',' ')) + ' · ' + zone,zone));$('timezone').value=defaultZone;
function updateDate(){const zone=$('timezone').value;const today=dateInZone(zone);$('birthday').max=today;$('header-date').textContent=today.replaceAll('-',' / ');$('header-weekday').textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:zone,weekday:'long'}).format(new Date())+' · 今日安好';$('year').textContent=today.slice(0,4);}
updateDate();
$('city').addEventListener('change',()=>{const zone=CITY_ZONES[normalizeCity($('city').value)];if(zone){$('timezone').value=zone;$('zone-hint').textContent='已匹配城市';}else{$('zone-hint').textContent='请确认当地时区';}updateDate();});$('timezone').addEventListener('change',updateDate);
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function render(o){$('demo-tag').hidden=true;$('result-label').textContent=o.date+' · 今日卦帖';$('result-city').textContent=o.city+' / '+o.mbti;$('fortune-kicker').textContent='今日签意 · '+o.word;$('fortune-title').replaceChildren(document.createTextNode(o.title[0]+'，'),el('br'),document.createTextNode(o.title[1]+'。'));$('fortune-summary').textContent=o.summary;$('fortune-level').textContent=o.level;$('fortune-element').textContent='今日关键词：'+o.word;$('symbol-name').textContent=o.symbol;$('trigram').replaceChildren(...o.lines.map(v=>el('i',undefined,v?'':'broken')));$('luck-strip').replaceChildren(...o.luck.map((l,i)=>{const d=el('div');d.append(el('span',['专注','人际','生活'][i]),el('strong',l[0]),el('em',l[1]));return d;}));$('actions').replaceChildren(...o.actions.map((a,i)=>{const d=el('div');const body=el('div');body.append(el('h4',a[0]),el('p',a[1]));d.append(el('span',['一','二'][i],'action-number'),body,el('span',a[2],'cost'));return d;}));$('avoid').textContent=o.avoid;$('meals').replaceChildren(...o.meals.map((m,i)=>{const d=el('div');d.append(el('span',['早 · 唤醒','午 · 满足','晚 · 松弛'][i]),el('h4',m[0]),el('p',m[1]));return d;}));const color=el('b');const dot=el('i');dot.style.background=o.color[1];color.append(dot,document.createTextNode(o.color[0]));$('lucky-color').replaceChildren(document.createTextNode('幸运色'),color);$('lucky-number').replaceChildren(document.createTextNode('幸运数字'),el('b',o.number));$('closing-line').textContent=o.date+' · 今天，也请善待自己。';$('oracle-card').classList.remove('refreshed');requestAnimationFrame(()=>$('oracle-card').classList.add('refreshed'));$('copy-status').textContent='';}
function profile(){return {birthday:$('birthday').value,city:$('city').value.trim(),mbti:$('mbti').value,timezone:$('timezone').value,diet:$('diet').value};}
function save(p){try{if($('remember').checked)localStorage.setItem(STORAGE_KEY,JSON.stringify(p));else localStorage.removeItem(STORAGE_KEY);return true;}catch{$('form-status').textContent='本机存储不可用，本次仍可正常生成卦帖。';return false;}}
$('oracle-form').addEventListener('submit',e=>{e.preventDefault();try{const p=profile();const o=generateOracle(p);activeOracle=o;activeProfile=p;render(o);if(save(p))$('form-status').textContent=$('remember').checked?'今日卦帖已生成，资料仅保存在本机。':'今日卦帖已生成，资料未保存。';if(matchMedia('(max-width:720px)').matches)$('result-label').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}catch(err){$('form-status').textContent=err.message;}});
$('remember').addEventListener('change',()=>{if(!$('remember').checked){try{localStorage.removeItem(STORAGE_KEY);$('form-status').textContent='已关闭记忆并清除本机保存的资料。';}catch{$('form-status').textContent='无法访问本机存储。';}}});
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const p=JSON.parse(raw);validateProfile(p);for(const key of ['birthday','city','mbti','timezone','diet'])$(key).value=p[key];$('remember').checked=true;activeProfile=p;activeOracle=generateOracle(p);render(activeOracle);updateDate();}}catch{try{localStorage.removeItem(STORAGE_KEY);}catch{}$('form-status').textContent='没有读取到有效资料，请重新填写。';}
$('clear-button').addEventListener('click',()=>{try{localStorage.removeItem(STORAGE_KEY);}catch{}$('oracle-form').reset();$('timezone').value=defaultZone;activeProfile=null;activeOracle=null;location.reload();});
$('copy-button').addEventListener('click',async()=>{if(!activeOracle){$('copy-status').textContent='请先填写资料，开启属于你的今日卦帖。';return;}try{await navigator.clipboard.writeText(oracleText(activeOracle));$('copy-status').textContent='已复制卦帖，不含生日。';}catch{$('copy-status').textContent='浏览器未允许复制，可使用“保存 / 打印”留存。';}});
$('print-button').addEventListener('click',()=>{if(!activeOracle){$('copy-status').textContent='请先填写资料，开启属于你的今日卦帖。';return;}window.print();});
$('about-button').addEventListener('click',()=>$('about-dialog').showModal());$('close-about').addEventListener('click',()=>$('about-dialog').close());
function refreshDay(){updateDate();if(activeProfile&&activeOracle&&dateInZone(activeProfile.timezone)!==activeOracle.date){activeOracle=generateOracle(activeProfile);render(activeOracle);$('form-status').textContent='新的一天，卦帖已更新。';}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshDay();});setInterval(refreshDay,60000);
