export const MBTIS = ['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];
export const CITY_ZONES = {'上海':'Asia/Shanghai','北京':'Asia/Shanghai','广州':'Asia/Shanghai','深圳':'Asia/Shanghai','成都':'Asia/Shanghai','杭州':'Asia/Shanghai','武汉':'Asia/Shanghai','南京':'Asia/Shanghai','西安':'Asia/Shanghai','重庆':'Asia/Shanghai','东京':'Asia/Tokyo','大阪':'Asia/Tokyo','京都':'Asia/Tokyo','香港':'Asia/Hong_Kong','台北':'Asia/Taipei','首尔':'Asia/Seoul','新加坡':'Asia/Singapore','伦敦':'Europe/London','巴黎':'Europe/Paris','柏林':'Europe/Berlin','纽约':'America/New_York','洛杉矶':'America/Los_Angeles','悉尼':'Australia/Sydney','墨尔本':'Australia/Melbourne','奥克兰':'Pacific/Auckland','迪拜':'Asia/Dubai','曼谷':'Asia/Bangkok','东京市':'Asia/Tokyo','shanghai':'Asia/Shanghai','beijing':'Asia/Shanghai','tokyo':'Asia/Tokyo','london':'Europe/London','new york':'America/New_York'};
export function normalizeCity(city) { return city.normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase(); }
export function dateInZone(timezone, now=new Date()) { const p=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now); return ['year','month','day'].map(t=>p.find(x=>x.type===t).value).join('-'); }
function hash(text) { let h=2166136261;for(const c of text){h^=c.codePointAt(0);h=Math.imul(h,16777619);}return h>>>0; }
const signs=[
{title:['心有余白','好事自来'],summary:'不必把每一刻填满。留一点空隙，让小小的惊喜有处落脚。',word:'留白',symbol:'风 · 自在',lines:[1,1,0],level:'小吉 · 从容的一天'},
{title:['循着微光','慢慢向前'],summary:'还没看清整条路也没关系。先完成眼前的一步，答案会在途中变得清楚。',word:'起步',symbol:'山 · 笃定',lines:[1,0,0],level:'渐吉 · 积蓄的一天'},
{title:['向阳而行','自有回响'],summary:'把一个小小的想法说出来，或开始一件惦记很久的事。今天的勇气，可以很轻。',word:'舒展',symbol:'火 · 明亮',lines:[1,0,1],level:'上吉 · 明亮的一天'},
{title:['与己相安','万物可亲'],summary:'把目光从别人的进度收回来。照顾好自己的节奏，就是今天值得做的事。',word:'安定',symbol:'地 · 包容',lines:[0,0,0],level:'平吉 · 安稳的一天'},
{title:['轻舟有信','好风徐来'],summary:'把一个迟迟没开始的小计划拆开。先做最容易的部分，让行动带来一点轻快。',word:'顺势',symbol:'水 · 流动',lines:[0,1,0],level:'中吉 · 轻快的一天'},
{title:['花开有时','不必着急'],summary:'有些事情值得等待。给正在生长的念头一点耐心，也给今天的自己一点肯定。',word:'耐心',symbol:'泽 · 愉悦',lines:[0,1,1],level:'小吉 · 温柔的一天'},
{title:['清风入怀','所遇皆新'],summary:'给熟悉的日常换一个小角度。一次新的尝试，或许会让今天变得不一样。',word:'好奇',symbol:'雷 · 萌动',lines:[0,0,1],level:'中吉 · 灵动的一天'},
{title:['日有小暖','心有所向'],summary:'把心意放进具体的小事里。一次真诚的回应、一顿认真吃的饭，都算今天的好事。',word:'连接',symbol:'天 · 生长',lines:[1,1,1],level:'上吉 · 和煦的一天'}
];
const focus=[['静心推进','给一件事完整的注意力'],['灵感渐近','先记下来，再慢慢整理'],['轻装起步','从最容易的一步开始'],['稳步积累','做完比做满更重要']];
const social=[['温柔相遇','给一句问候留点空间'],['自在相处','按舒服的节奏来往'],['心意有声','把感谢说得具体一些'],['留白也好','安静相伴也是连接']];
const life=[['小有惊喜','留意日常里的好风景'],['从容有序','整理一处小小的角落'],['松弛有度','给空闲留一点位置'],['安稳舒心','认真吃饭，慢慢生活']];
const actionBank={I:[['为自己留十分钟','合上多余的页面，安静完成一件小事。','10 分钟'],['写下今天的小发现','用三句话，留住一个值得记住的瞬间。','5 分钟']],E:[['发出一句真诚问候','想起谁，就给对方留一句轻松的问候。','2 分钟'],['分享一件开心小事','把今天的小收获，讲给愿意听的人。','5 分钟']],N:[['留住一个新念头','把脑海里的想法写下来，不急着评判。','3 分钟'],['换个角度看日常','从熟悉的事里，找出一个没留意过的细节。','5 分钟']],S:[['整理一小块桌面','只收好眼前的东西，为自己腾一点空间。','5 分钟'],['完成一个小收尾','把一件快完成的事收好，给今天一个句号。','10 分钟']]};
const avoids=['不急着答应每一个邀请，也不必为休息找理由。','先把手头的一件事做完，再打开新的待办清单。','别用别人的进度，催促自己的步伐。','不必反复揣测一句话，留一点空间给直接沟通。','先放一放不急的决定，等思路清楚再继续。','不把一天的小插曲，当作对自己的评价。'];
const breakfasts=[['燕麦水果碗','清淡开场，慢慢进入今天。'],['豆浆与蔬菜包','熟悉的热气，简单的早晨。'],['鸡蛋全麦吐司','做一份简单的晨间小餐。'],['小米粥与蒸南瓜','一碗暖意，开启平常的一天。'],['酸奶水果杯','酸甜一口，给早晨一点变化。']];
const lunches=[['番茄豆腐饭','熟悉的滋味，安稳的日常。'],['菌菇时蔬饭','把不同的颜色装进碗里。'],['蔬菜鸡蛋面','一碗热面，也可以很满足。'],['南瓜鹰嘴豆碗','给平常的午餐换个口味。']];
const dinners=[['菌菇蔬菜面','把今天，收在一碗热气里。'],['番茄鸡蛋汤配米饭','家常的味道，适合慢慢吃。'],['杂蔬豆腐煲配米饭','留一点时间，享受一顿热饭。'],['香菇青菜粥配蒸蛋','用柔和的滋味，为今天收尾。']];
const colors=[['鼠尾草绿','#97a987'],['月白','#e4e9e1'],['燕麦色','#d9cbaa'],['雾蓝','#9bafb7'],['藕粉','#c6a5a0'],['浅杏','#e2c49e']];
export function validateProfile(p,now=new Date()) {if(!p||typeof p.city!=='string'||!normalizeCity(p.city)||p.city.length>60)throw new Error('请填写 1–60 字的城市名称。');if(!MBTIS.includes(p.mbti))throw new Error('请选择一个 MBTI 类型。');if(!['all','vegetarian'].includes(p.diet))throw new Error('请选择饮食偏好。');let today;try{today=dateInZone(p.timezone,now);}catch{throw new Error('请选择有效的当地时区。');}if(!/^\d{4}-\d{2}-\d{2}$/.test(p.birthday)||p.birthday<'1900-01-01'||p.birthday>today)throw new Error('请填写 1900 年起、不晚于今天的公历生日。');const d=new Date(p.birthday+'T12:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==p.birthday)throw new Error('请填写有效的公历日期。');return today;}
export function generateOracle(p,now=new Date()) {const date=validateProfile(p,now);const seed=`rihe-v1|${date}|${p.birthday}|${normalizeCity(p.city)}|${p.mbti}`;const pick=(key,items)=>items[hash(seed+'|'+key)%items.length];const sign=pick('sign',signs);const meals=[pick('breakfast',breakfasts),pick('lunch',p.diet==='vegetarian'?lunches:[...lunches,['香煎鸡肉饭','一份家常午饭，认真吃好。'],['清蒸鱼配米饭','简单烹调，尝一尝原本的滋味。']]),pick('dinner',p.diet==='vegetarian'?dinners:[...dinners,['冬瓜鸡肉汤配米饭','一碗热汤，留给晚间的自己。']])];return {date,city:p.city.trim(),mbti:p.mbti,...sign,luck:[pick('focus',focus),pick('social',social),pick('life',life)],actions:[pick('action1',actionBank[p.mbti[0]]),pick('action2',actionBank[p.mbti[1]])],avoid:pick('avoid',avoids),meals,color:pick('color',colors),number:1+hash(seed+'|number')%9};}
export function oracleText(o){return `日和 · 每日卦帖\n${o.date} · ${o.city} · ${o.mbti}\n\n${o.title.join('，')}。\n${o.level}｜关键词：${o.word}\n${o.summary}\n\n宜\n${o.actions.map(a=>`${a[0]}（${a[2]}）：${a[1]}`).join('\n')}\n缓一缓：${o.avoid}\n\n今日食笺\n${o.meals.map((m,i)=>['早','午','晚'][i]+'：'+m[0]).join('\n')}\n幸运色：${o.color[0]} · 幸运数字：${o.number}\n\n签意仅供娱乐与自我关照；食笺仅作选餐灵感，请按过敏与忌口调整。`;}
